//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubricaTelefonica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contatto
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string indirizzo { get; set; }
        public byte[] foto { get; set; }
        public Nullable<System.DateTime> data_nascita { get; set; }
        public Nullable<bool> preferito { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
